import { ListChecksIcon } from "lucide-react";
import { ADMINS } from "@/lib/app-config";
import { PRIORITY, STATUS, TEAMS } from "./options";
import { defineTable } from "./schema";

export const taskTable = defineTable({
  name: "task",
  label: "Tasks",
  description: "Reporting team task tracker",
  icon: ListChecksIcon,
  excel: {
    url: "https://megascale-my.sharepoint.com/:x:/g/personal/sami_megascale_onmicrosoft_com/IQCPCZmoJZtNQa19KJT6oa5mAd4PeXGMjLy2Ogu9CI5r424?e=d4K5TE",
    table: "Tasks",
  },
  images: {
    url: "https://megascale-my.sharepoint.com/:f:/g/personal/sami_megascale_onmicrosoft_com/IgD8JNcjkVNZQqHDmxTDytFlAUlyyQeeVqvmXIglzFeH7aU?e=oJ5KPA",
  },
  writers: ADMINS,
  columns: [
    { name: "name", label: "Title", type: "string", required: true },
    { name: "status", label: "Status", type: "option", options: STATUS },
    { name: "priority", label: "Priority", type: "option", options: PRIORITY },
    {
      name: "team",
      label: "Team",
      type: "option",
      options: TEAMS,
      multiple: true,
    },
    { name: "owner", label: "Owner", type: "string" },
    { name: "due_date", label: "Due date", type: "date" },
    { name: "estimate", label: "Effort (d)", type: "number" },
    { name: "blocking", label: "Blocking", type: "boolean" },
    { name: "link", label: "Link", type: "url" },
    { name: "description", type: "text" },
    { name: "screenshot", label: "Screenshot", type: "image" },
  ],
  defaultColumns: ["status", "priority", "owner", "due_date"],
  kpi: { field: "status", values: ["to_do", "in_progress", "done"] },
  sort: { column: "due_date", direction: "asc" },
  filters: { options: { status: ["to_do", "in_progress", "to_validate"] } },
  sample: [
    {
      name: "Report redesign",
      status: "in_progress",
      priority: "high",
      team: ["data", "finance"],
      owner: "Camille",
      due_date: "2026-10-20",
      estimate: 8,
      blocking: false,
      link: "https://app.powerbi.com",
      description: "New **overview** page + drill-through by region.",
      screenshot: null,
    },
    {
      name: "Automate the monthly export",
      status: "to_do",
      priority: "medium",
      team: ["ops"],
      owner: "Yanis",
      due_date: "2026-11-02",
      estimate: 3,
      blocking: false,
      link: null,
      description: "Power Automate flow triggered on the 1st of the month.",
      screenshot: null,
    },
    {
      name: "Fix the margin calculation",
      status: "to_validate",
      priority: "high",
      team: ["finance"],
      owner: "Inès",
      due_date: "2026-10-08",
      estimate: 1.5,
      blocking: true,
      link: null,
      description: "The DAX measure ignores credit notes.",
      screenshot: null,
    },
    {
      name: "HR user guide",
      status: "done",
      priority: "low",
      team: ["rh"],
      owner: "Léa",
      due_date: "2026-09-15",
      estimate: 2,
      blocking: false,
      link: null,
      description: "Guided presentation of the HR dashboard.",
      screenshot: null,
    },
    {
      name: "SharePoint sources migration",
      status: "in_progress",
      priority: "medium",
      team: ["data", "ops"],
      owner: "Camille",
      due_date: "2026-10-30",
      estimate: 5,
      blocking: false,
      link: null,
      description: "",
      screenshot: null,
    },
    {
      name: "Multi-site filter",
      status: "canceled",
      priority: "low",
      team: ["ops"],
      owner: "Yanis",
      due_date: null,
      estimate: null,
      blocking: false,
      link: null,
      description: "Replaced by a synced slicer.",
      screenshot: null,
    },
  ],
});
